const forcedRole=document.body.dataset.catosRole||null;
const loginParam=new URLSearchParams(location.search).get('login')==='1';
if(forcedRole&&loginParam)sessionStorage.setItem('catos-login-role',forcedRole);
if(forcedRole&&sessionStorage.getItem('catos-login-role')!==forcedRole){location.replace('/');}
if(loginParam)history.replaceState({},'',location.pathname);
let courses=JSON.parse(localStorage.getItem('catos-schedule')||'null')||[
 {id:'ds101',time:'09:00 — 10:30',day:'月曜',period:'1限',name:'データサイエンス基礎',room:'B-203',teacher:'佐藤先生',status:'done'},
 {id:'ai201',time:'10:45 — 12:15',day:'月曜',period:'2限',name:'AIプログラミング演習',room:'PC-04',teacher:'田中先生',status:'current'},
 {id:'stat',time:'13:10 — 14:40',day:'月曜',period:'3限',name:'統計解析 I',room:'A-104',teacher:'山本先生',status:'upcoming'},
 {id:'design',time:'14:55 — 16:25',day:'月曜',period:'4限',name:'サービスデザイン',room:'D-301',teacher:'小林先生',status:'upcoming'},
 {id:'ethics',time:'09:00 — 10:30',day:'火曜',period:'1限',name:'情報倫理',room:'C-102',teacher:'森先生',status:'upcoming'},
 {id:'seminar',time:'10:45 — 12:15',day:'水曜',period:'2限',name:'データ活用演習',room:'研究室',teacher:'佐藤先生',status:'upcoming'},
 {id:'math',time:'13:10 — 14:40',day:'木曜',period:'3限',name:'線形代数',room:'B-102',teacher:'高橋先生',status:'upcoming'},
 {id:'project',time:'14:55 — 16:25',day:'金曜',period:'4限',name:'PBLプロジェクト',room:'ラボ 02',teacher:'中村先生',status:'upcoming'}
];
const defaultHistory=[{course:'データサイエンス基礎',date:'2026/09/28',time:'08:56',result:'出席',method:'CATOS'}];
const defaultSettings={autoSync:true,confirmPunch:true,localHistory:true,notifications:true};
const state={view:'today',selected:null,history:JSON.parse(localStorage.getItem('catos-history')||'null')||defaultHistory,lastSync:localStorage.getItem('catos-sync')||'09:42',account:JSON.parse(sessionStorage.getItem('catos-account')||'null'),settings:{...defaultSettings,...JSON.parse(localStorage.getItem('catos-settings')||'{}')}};
const root=document.getElementById('viewRoot');
if(state.account&&forcedRole)state.account.role=forcedRole;
const titles={today:['TODAY / OVERVIEW','今日の運用'],timetable:['WORKSPACE / TIMETABLE','時間割'],courses:['WORKSPACE / COURSES','履修・授業'],history:['WORKSPACE / ATTENDANCE LOG','出席履歴'],sync:['SYSTEM / SYNC CENTER','同期センター'],settings:['SYSTEM / SETTINGS','設定']};
function save(){if(state.settings.localHistory)localStorage.setItem('catos-history',JSON.stringify(state.history));else localStorage.removeItem('catos-history');localStorage.setItem('catos-schedule',JSON.stringify(courses));localStorage.setItem('catos-sync',state.lastSync);localStorage.setItem('catos-settings',JSON.stringify(state.settings));if(state.account)sessionStorage.setItem('catos-account',JSON.stringify(state.account))}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function initials(name='CATOS'){return name.trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function roleLabel(role){return role==='faculty'?'教員アカウント':role==='admin'?'事務アカウント':'学生アカウント'}
function updateProfile(){if(!state.account)return;const name=state.account.displayName||'CATOSユーザー';const campus=state.account.campus||'大阪成蹊大学';document.getElementById('sideName').textContent=name;document.getElementById('topName').textContent=name;document.getElementById('sideRole').textContent=roleLabel(state.account.role);document.getElementById('sideCampus').textContent=campus;document.getElementById('sideAvatar').textContent=initials(name);document.getElementById('topAvatar').textContent=initials(name)}
function statusFor(c){if(state.history.some(h=>h.course===c.name&&h.date==='2026/09/28'))return 'done';return c.status}
function courseCard(c){const s=statusFor(c);return `<article class="class-card ${s}"><div class="class-time">${c.time}</div><h3>${c.name}</h3><p>${c.room} · ${c.teacher}</p>${s==='done'?'<span class="card-status"><span class="mini-check">✓</span> 記録済み</span>':s==='current'?'<span class="card-status">● 受付中 · 今ここ</span>':'<span class="card-status">○ 受付開始前</span>'}${s==='current'?`<button class="button mint card-action" data-punch="${c.id}">出席する</button>`:''}</article>`}
function renderToday(){const today=courses.slice(0,4),done=state.history.length,rate=Math.round(done/8*100),role=state.account?.role||'student',audience=role==='admin'?'事務モード · 全体データを管理':role==='faculty'?'教員モード · 担当授業を確認':'学生モード · 自分の出席を管理';return `<div class="hero-grid"><div class="hero-card"><p class="eyebrow">MONDAY, SEPTEMBER 28 2026</p><span class="role-badge ${role}">${audience}</span><h1 class="hero-title">今日の運用を、<br><em>ひとつずつ</em>確実に。</h1><p class="hero-lede">授業の出席状況と次のアクションをまとめています。ActiveAcademyで記録していた「授業選択 → 認証 → 送信」の流れを、迷わない画面に整えました。</p><button class="button primary" data-view="timetable">時間割を確認する <span>→</span></button></div><aside class="hero-stat-card"><span class="stat-label">TODAY'S ATTENDANCE</span><div class="big-stat">${done}<span> / 4 records</span></div><div class="stat-foot"><span>今週の出席率</span><strong>${rate}%</strong></div><div class="progress"><i style="width:${Math.min(rate,100)}%"></i></div><div class="stat-foot"><span>同期状態</span><strong>正常</strong></div></aside></div><div class="section-head"><div><p class="eyebrow">NEXT IN LINE</p><h2>今日の時間割</h2></div><button class="button ghost" data-view="timetable">すべて見る →</button></div><div class="schedule-grid">${today.map(courseCard).join('')}</div><div class="section-head"><div><p class="eyebrow">AT A GLANCE</p><h2>出席サマリー</h2></div></div><div class="kpi-grid"><div class="kpi"><small>今週の出席率</small><strong>${rate}<span>%</span></strong><div class="progress"><i style="width:${rate}%"></i></div></div><div class="kpi"><small>記録済みの授業</small><strong>${done}<span> / 8</span></strong><div class="progress"><i style="width:${done/8*100}%"></i></div></div><div class="kpi"><small>最終同期</small><strong>${state.lastSync}</strong><p class="muted">すべての端末で最新です</p></div></div>`}
function renderTimetable(){return `<div class="view-heading"><p class="eyebrow">WORKSPACE / WEEKLY SCHEDULE</p><h1 class="view-title">時間割</h1><p class="view-subtitle">今週の授業と、出席の受付状態を確認します。</p></div><div class="section-head"><div><p class="eyebrow">MONDAY / 09.28</p><h2>月曜日</h2></div><button class="button mint" data-punch="ai201">受付中の授業を記録</button></div><div class="schedule-grid">${courses.slice(0,4).map(courseCard).join('')}</div><div class="section-head"><div><p class="eyebrow">TUESDAY — FRIDAY</p><h2>今週の予定</h2></div></div><div class="table-card"><table class="course-table"><thead><tr><th>曜日 / 時限</th><th>授業</th><th>教室</th><th>担当</th><th>状態</th></tr></thead><tbody>${courses.slice(4).map(c=>`<tr><td>${c.day} ${c.period}</td><td><strong>${c.name}</strong></td><td>${c.room}</td><td>${c.teacher}</td><td><span class="pill blue">予定</span></td></tr>`).join('')}</tbody></table></div>`}
function renderCourses(){return `<div class="view-heading"><p class="eyebrow">WORKSPACE / ENROLLMENT CACHE</p><h1 class="view-title">履修・授業</h1><p class="view-subtitle">ポータルから同期された履修情報を、端末内のキャッシュとして表示しています。</p></div><div class="section-head"><div><p class="eyebrow">8 COURSES · HASH VERIFIED</p><h2>履修一覧</h2></div><button class="button mint" id="syncNow">履修を同期</button></div><div class="table-card"><table class="course-table"><thead><tr><th>コード</th><th>授業名</th><th>曜日 / 時限</th><th>教室</th><th>状態</th></tr></thead><tbody>${courses.map((c,i)=>`<tr><td><span class="pill">${['DS-101','AI-201','ST-202','SD-204','IT-101','DS-302','MA-201','PBL-401'][i]}</span></td><td><strong>${c.name}</strong></td><td>${c.day} ${c.period}</td><td>${c.room}</td><td><span class="pill blue">履修中</span></td></tr>`).join('')}</tbody></table></div>`}
function renderHistory(){return `<div class="view-heading"><p class="eyebrow">WORKSPACE / ATTENDANCE LOG</p><h1 class="view-title">出席履歴</h1><p class="view-subtitle">CATOSから送信した出席記録を端末内に保存しています。</p></div><div class="insight-grid"><div class="chart-card"><div class="section-head" style="margin:0"><div><p class="eyebrow">THIS WEEK</p><h2>週間の出席状況</h2></div><span class="pill">${state.history.length} records</span></div><div class="chart">${['月','火','水','木','金'].map((d,i)=>`<div class="bar-wrap"><div class="bar ${i===0?'active':''}" style="height:${[90,72,88,58,78][i]}%"></div><small>${d}</small></div>`).join('')}</div></div><div class="info-card"><p class="eyebrow">RECENT ACTIVITY</p><div class="notice-list">${state.history.slice(0,3).map(h=>`<div class="notice"><div class="notice-icon">✓</div><div><strong>${h.course}</strong><p>${h.date} ${h.time} · ${h.result}</p></div></div>`).join('')}</div></div></div><div class="section-head"><div><p class="eyebrow">FULL LOG</p><h2>記録一覧</h2></div></div><div class="table-card"><table class="course-table"><thead><tr><th>日時</th><th>授業</th><th>結果</th><th>方法</th></tr></thead><tbody>${state.history.map(h=>`<tr><td>${h.date} ${h.time}</td><td><strong>${h.course}</strong></td><td><span class="pill">${h.result}</span></td><td>${h.method}</td></tr>`).join('')}</tbody></table></div>`}
function renderSync(){return `<div class="view-heading"><p class="eyebrow">SYSTEM / LOCAL-FIRST SYNC</p><h1 class="view-title">同期センター</h1><p class="view-subtitle">外部サービスがなくても、現在の端末上でデータを確認・復元できます。</p></div><div class="hero-card" style="margin-top:30px"><p class="eyebrow">PORTAL CONNECTION</p><h2 style="margin:0;font-size:24px">大阪成蹊大学ポータル</h2><p class="hero-lede">ActiveAcademyのリトライ付き取得・履修変更検知の考え方を、CATOSでは接続状態とキャッシュの可視化に置き換えています。</p><div class="kpi-grid"><div class="kpi"><small>接続状態</small><strong style="color:#2f9c68;font-size:20px">● 正常</strong></div><div class="kpi"><small>履修キャッシュ</small><strong>8<span> courses</span></strong></div><div class="kpi"><small>最終同期</small><strong>${state.lastSync}</strong></div></div><div style="margin-top:22px"><button class="button primary" id="syncNow">今すぐ同期する →</button></div></div>`}
function toggleSetting(key){state.settings[key]=!state.settings[key];save();render();toast(`${settingLabels[key]}を${state.settings[key]?'オン':'オフ'}にしました`)}
const settingLabels={autoSync:'自動同期',confirmPunch:'出席送信の確認',localHistory:'ローカル履歴',notifications:'通知'};
function renderSettings(){const a=state.account||{};const canImport=a.role==='faculty'||a.role==='admin';return `<div class="view-heading"><p class="eyebrow">SYSTEM / PREFERENCES + LOCAL BACKEND</p><h1 class="view-title">設定</h1><p class="view-subtitle">変更はすぐにこの端末へ保存され、次回起動時にも反映されます。</p></div><div class="settings-grid settings-live" style="margin-top:30px">${Object.entries(settingLabels).map(([key,label])=>`<button class="setting setting-button" data-setting="${key}"><div><h3>${label}</h3><p>${key==='autoSync'?'アプリを開いたときに履修情報を確認':key==='confirmPunch'?'送信前にパスワード入力を確認':key==='localHistory'?'この端末に出席履歴を保存':'同期や送信結果を通知'}</p></div><span class="toggle ${state.settings[key]?'on':'off'}"></span></button>`).join('')}</div><div class="section-head"><div><p class="eyebrow">ACCOUNT PROFILE</p><h2>アカウント情報</h2></div><button class="button ghost" id="resetAccount">アカウントを切り替える</button></div><div class="account-settings-card"><form id="profileForm" class="profile-form"><label>表示名<input name="displayName" required maxlength="30" value="${a.displayName||''}"></label><label>大学ID / 学籍番号<input name="accountId" required maxlength="40" value="${a.accountId||''}"></label><label>所属キャンパス<select name="campus"><option ${a.campus==='大阪成蹊大学'?'selected':''}>大阪成蹊大学</option><option ${a.campus==='大阪成蹊短期大学'?'selected':''}>大阪成蹊短期大学</option><option ${a.campus==='その他'?'selected':''}>その他</option></select></label><label>アカウント種別<select name="role"><option value="student" ${a.role==='student'?'selected':''}>学生</option><option value="faculty" ${a.role==='faculty'?'selected':''}>教員</option><option value="admin" ${a.role==='admin'?'selected':''}>事務</option></select></label><button class="button primary" type="submit">アカウント情報を保存</button></form><div class="storage-note"><span class="status-dot"></span><div><strong>${roleLabel(a.role||'student')}</strong><p>アカウントはこのタブのセッションだけに保存。設定・履歴は端末内に保存されます。</p></div></div></div><div class="section-head"><div><p class="eyebrow">DATA PORTABILITY</p><h2>データ入出力</h2></div></div><div class="io-card"><div><strong>時間割データ</strong><p>現在の時間割をCSV / JSONで保存、またはファイルから読み込みます。</p><div class="io-actions"><button class="button ghost" data-export="schedule-csv">CSVを書き出す</button><button class="button ghost" data-export="schedule-json">JSONを書き出す</button>${canImport?'<button class="button mint" data-import="schedule">時間割を読み込む</button>':'<span class="pill blue">学生は閲覧のみ</span>'}</div></div><div><strong>出席履歴</strong><p>${state.account?.role==='student'?'自分の出席履歴':'管理対象の出席履歴'}をCSV / JSONで保存できます。</p><div class="io-actions"><button class="button ghost" data-export="history-csv">CSVを書き出す</button><button class="button ghost" data-export="history-json">JSONを書き出す</button>${canImport?'<button class="button mint" data-import="history">履歴を読み込む</button>':'<span class="pill blue">自分の履歴のみ</span>'}</div></div></div><div class="danger-zone"><div><strong>デモデータを初期化</strong><p>出席履歴と設定を初期状態に戻します。アカウントは保持します。</p></div><button class="button ghost" id="clearDemo">履歴を初期化</button></div>`} 

function csvEscape(value){const text=String(value??'');return /[",\n]/.test(text)?'"'+text.replace(/"/g,'""')+'"':text}
function toCsv(rows,headers){return [headers.join(','),...rows.map(row=>headers.map(h=>csvEscape(row[h])).join(','))].join('\n')}
function downloadText(text,name,type){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
function exportData(kind,format){const isSchedule=kind==='schedule';const rows=isSchedule?courses:state.history;const headers=isSchedule?['id','time','day','period','name','room','teacher','status']:['course','date','time','result','method'];const stamp=new Date().toISOString().slice(0,10);if(format==='json'){downloadText(JSON.stringify({type:kind,exportedAt:new Date().toISOString(),data:rows},null,2),`CATOS_${kind}_${stamp}.json`,'application/json')}else{downloadText(toCsv(rows,headers),`CATOS_${kind}_${stamp}.csv`,'text/csv;charset=utf-8')}toast(`${isSchedule?'時間割':'出席履歴'}を${format.toUpperCase()}で書き出しました`)}
function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const parse=line=>{const out=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cur+='"';i++;}else if(c==='"'){quoted=!quoted;}else if(c===','&&!quoted){out.push(cur);cur='';}else cur+=c}out.push(cur);return out};const headers=parse(lines[0]);return lines.slice(1).map(line=>{const vals=parse(line),row={};headers.forEach((h,i)=>row[h]=vals[i]||'');return row})}
function importData(file,type){const reader=new FileReader();reader.onload=()=>{try{let parsed;if(file.name.toLowerCase().endsWith('.json')){const json=JSON.parse(reader.result);parsed=Array.isArray(json)?json:(json.data||[])}else parsed=parseCsv(reader.result);if(type==='schedule'){const valid=parsed.filter(x=>x.name&&x.day).map((x,i)=>({...x,id:x.id||`imported-${Date.now()}-${i}`,status:x.status||'upcoming'}));if(!valid.length)throw new Error('時間割のname/day列が必要です');courses=valid}else{const valid=parsed.filter(x=>x.course&&x.date).map(x=>({...x,result:x.result||'出席',method:x.method||'import'}));if(!valid.length)throw new Error('履歴のcourse/date列が必要です');state.history=valid}save();render();toast(`${type==='schedule'?'時間割':'出席履歴'}を読み込みました`)}catch(error){toast(`読み込みに失敗しました: ${error.message}`)}document.getElementById('importFile').value=''};reader.readAsText(file)}
function render(){root.innerHTML={today:renderToday,timetable:renderTimetable,courses:renderCourses,history:renderHistory,sync:renderSync,settings:renderSettings}[state.view]();document.getElementById('pageKicker').textContent=titles[state.view][0];document.getElementById('pageTitle').textContent=titles[state.view][1];updateProfile();root.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>goTo(b.dataset.view)));root.querySelectorAll('[data-punch]').forEach(b=>b.addEventListener('click',()=>openPunch(b.dataset.punch)));const sync=document.getElementById('syncNow');if(sync)sync.addEventListener('click',syncNow);root.querySelectorAll('[data-setting]').forEach(b=>b.addEventListener('click',()=>toggleSetting(b.dataset.setting)));const pf=document.getElementById('profileForm');if(pf)pf.addEventListener('submit',saveProfile);const reset=document.getElementById('resetAccount');if(reset)reset.addEventListener('click',resetAccount);const clear=document.getElementById('clearDemo');if(clear)clear.addEventListener('click',clearDemo);root.querySelectorAll('[data-export]').forEach(b=>b.addEventListener('click',()=>{const [kind,format]=b.dataset.export.split('-');exportData(kind,format)}));root.querySelectorAll('[data-import]').forEach(b=>b.addEventListener('click',()=>{state.importType=b.dataset.import;document.getElementById('importFile').click()}))}
function goTo(view){state.view=view;document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));render();window.scrollTo(0,0)}
function openPunch(id){state.selected=courses.find(c=>c.id===id);if(!state.settings.confirmPunch){submitPunch();return}document.getElementById('dialogCourse').textContent=state.selected.name;document.getElementById('dialogMeta').textContent=`${state.selected.day} ${state.selected.period} · ${state.selected.room} · ${state.selected.teacher}`;document.getElementById('attendancePassword').value='';document.getElementById('punchDialog').showModal()}
function submitPunch(){if(!state.selected)return;const now=new Date();state.history.unshift({course:state.selected.name,date:'2026/09/28',time:now.toTimeString().slice(0,5),result:'出席',method:'CATOS'});state.lastSync=now.toTimeString().slice(0,5);save();if(document.getElementById('punchDialog').open)document.getElementById('punchDialog').close();toast(`${state.selected.name} の出席を記録しました`);state.view='today';render()}
function syncNow(){const now=new Date();state.lastSync=now.toTimeString().slice(0,5);save();toast('履修情報を同期しました');render()}
function saveProfile(e){e.preventDefault();const data=new FormData(e.target);state.account={displayName:data.get('displayName').trim(),accountId:data.get('accountId').trim(),campus:data.get('campus'),role:forcedRole||data.get('role')};save();updateProfile();toast('アカウント情報を保存しました');render()}
function resetAccount(){sessionStorage.removeItem('catos-account');sessionStorage.removeItem('catos-login-role');window.location.href='/'}
function clearDemo(){if(!confirm('出席履歴と設定を初期化しますか？'))return;state.history=defaultHistory;state.settings={...defaultSettings};save();toast('デモデータを初期化しました');render()}
function showOnboarding(force=false){const o=document.getElementById('onboarding');if(force)o.hidden=false;o.classList.add('visible');document.getElementById('app').classList.add('behind-overlay')}
function finishOnboarding(form){const data=new FormData(form);state.account={displayName:data.get('displayName').trim(),accountId:data.get('accountId').trim(),campus:data.get('campus'),role:forcedRole||data.get('role')};save();const o=document.getElementById('onboarding');o.classList.remove('visible');setTimeout(()=>{o.hidden=true;document.getElementById('app').classList.remove('behind-overlay');updateProfile();render();toast(`ようこそ、${state.account.displayName}さん`);},420)}
document.getElementById('accountForm').addEventListener('submit',e=>{e.preventDefault();finishOnboarding(e.target)});
document.getElementById('profileForm');
document.getElementById('punchForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();submitPunch()});
document.querySelectorAll('.nav-item').forEach(n=>n.addEventListener('click',()=>goTo(n.dataset.view)));document.getElementById('notifyBtn').addEventListener('click',()=>toast(state.settings.notifications?'新しい通知はありません':'通知はオフになっています'));document.getElementById('profileBtn').addEventListener('click',()=>goTo('settings'));document.getElementById('logoutBtn').addEventListener('click',()=>resetAccount());
document.getElementById('importFile').addEventListener('change',e=>{if(e.target.files[0])importData(e.target.files[0],state.importType||'history')});
function boot(){updateProfile();render();setTimeout(()=>{document.getElementById('splash').classList.add('hide');setTimeout(()=>{document.getElementById('splash').remove();if(!state.account)showOnboarding()},430)},1100)}
boot();
